@authKey = ttbwoosuk2881547001
http://www.aladin.co.kr/ttb/api/ItemList.aspx?ttbkey={{authKey}}&QueryType=ItemNewSpecial&MaxResults=30&start=1&SearchTarget=Book&output=js&Version=20131101&Cover=Big

###
# Bestseller 
http://www.aladin.co.kr/ttb/api/ItemList.aspx?ttbkey={{authKey}}&QueryType=Bestseller&MaxResults=30&start=1&SearchTarget=Book&output=js&Version=20131101&Cover=Big


###
# BlogBest 

http://www.aladin.co.kr/ttb/api/ItemList.aspx?ttbkey={{authKey}}&QueryType=BlogBest&MaxResults=30&start=1&SearchTarget=Book&output=js&Version=20131101&Cover=Big
